version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      got-api-network:
        ipv4_address: 172.16.0.2

  app:
    build: ./
    image: got-api:develop
    container_name: got-api
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    volumes:
      - ./src:/app/src
    ports:
      - 8000:80
    networks:
      got-api-network:
        ipv4_address: 172.16.0.3
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local

networks:
  got-api-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1
